AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: student-api

Globals:
  Function:
    Timeout: 3

Resources:
  StudentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: students-data-frontend

  StudentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: students
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  StudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: students/
      Handler: app.app
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref StudentTable
      Events:
        Test:
          Type: Api
          Properties:
            Path: /
            Method: get
        ListStudents:
          Type: Api
          Properties:
            Path: /students
            Method: get
        PutStudent:
          Type: Api
          Properties:
            Path: /students
            Method: post
        GetStudent:
          Type: Api
          Properties:
            Path: /students/{id}/
            Method: get
        PatchStudent:
          Type: Api
          Properties:
            Path: /students/{id}/
            Method: patch
        DeleteStudent:
          Type: Api
          Properties:
            Path: /students/{id}/
            Method: delete


Outputs:
  StudentApi:
    Description: "API Gateway endpoint URL for Prod stage for Student function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  StudentFunction:
    Description: "Student Lambda Function ARN"
    Value: !GetAtt StudentFunction.Arn
  StudentFunctionIamRole:
    Description: "Implicit IAM Role created for Student function"
    Value: !GetAtt StudentFunctionRole.Arn
